### ISSUE TITLE
Redesign Homepage and Signup Flows

### ISSUE THREAD

**Issue by caillou** [teachen-ch/voty#82]
When navigating demo.voty.ch it took me quite a while to figure out how to register an account.

My intuition was to look for a `Registrieren` button close to the `Anmelden` button.

I actually had to read the FAQ to figure out that `Jetzt Klasse anmelden!` was the button I hat do click.

Maybe consider adding a `Registrieren` button or link to the right of `Anmelden`.

**Comment by stefnnn** [comment]
You do have a point @caillou. There was a `Registrieren` Button indeed right next to `Anmelden`. Turned out, that students, which were invited into their class by the teacher with a special invite-link used the `Registrieren` Button as well, even though it clearly said that it was only for teachers. But it's definitely an area for improvement and I'll keep the issue open to remind us of that 👍

**Comment by stefnnn** [comment]
Implemented in relaunch of website
